import { Incident, HOTELS } from "@/types/incident";

// Sample reports so the dashboard has something to show immediately
export const MOCK_INCIDENTS: Incident[] = [
  {
    id: "1",
    report_number: "26-INC-10017",
    hotel_id: "10",
    incident_type: "guest_injury",
    severity: "low",
    incident_date_time: "2026-08-09T11:00",
    reported_date_time: "2026-08-09T11:40",
    location_detail: "Guest Room, 949",
    subject_name: "Dearcy Shenard Livington",
    subject_type: "Guest",
    subject_identifier: "949",
    subject_phone: "",
    subject_email: "",
    witness_name: "Shanley Simpson",
    witness_contact: "832-792-8269",
    narrative:
      "The additional guest in room 949 scraped his right leg on the metal bedframe sticking out from under the box frame and mattress. Guest wanted to make a report about the incident. The guest didn't require any medical attention.",
    actions_taken: "Report taken. Photos of injury captured by Front Desk.",
    contributing_factors: "Bracket under bed / metal bed frame sticking out",
    miscellaneous: "",
    ems_called: false,
    medical_refused: false,
    police_involved: false,
    status: "submitted",
    created_at: "2026-08-09T11:50:00Z",
    updated_at: "2026-08-09T11:50:00Z",
    reported_by_name: "Mark Chance (Front Desk)",
    hotel: HOTELS.find((h) => h.id === "10"),
  },
  {
    id: "2",
    report_number: "26-INC-10018",
    hotel_id: "5",
    incident_type: "near_miss",
    severity: "medium",
    incident_date_time: "2026-08-08T16:30",
    reported_date_time: "2026-08-08T16:45",
    location_detail: "Loading dock",
    subject_name: "N/A",
    subject_type: "Other",
    subject_identifier: "",
    subject_phone: "",
    subject_email: "",
    witness_name: "James Rivera",
    witness_contact: "",
    narrative:
      "Delivery truck almost backed into a parked associate vehicle. No contact was made. Spotter was not in place at the time.",
    actions_taken: "Spoke with driver. Reviewed dock safety procedure with team.",
    contributing_factors: "No spotter in place",
    miscellaneous: "Will add reminder signage.",
    ems_called: false,
    medical_refused: false,
    police_involved: false,
    status: "under_review",
    created_at: "2026-08-08T16:50:00Z",
    updated_at: "2026-08-08T17:10:00Z",
    reported_by_name: "Sarah Chen",
    hotel: HOTELS.find((h) => h.id === "5"),
  },
  {
    id: "3",
    report_number: "26-INC-10019",
    hotel_id: "1",
    incident_type: "property_damage",
    severity: "medium",
    incident_date_time: "2026-08-07T09:15",
    reported_date_time: "2026-08-07T09:30",
    location_detail: "Lobby chandelier",
    subject_name: "",
    subject_type: "Other",
    subject_identifier: "",
    subject_phone: "",
    subject_email: "",
    witness_name: "",
    witness_contact: "",
    narrative:
      "Housekeeping cart bumped the lower tier of the lobby chandelier during early morning cleaning. One crystal piece cracked.",
    actions_taken: "Area cordoned. Engineering notified. Photo taken.",
    contributing_factors: "Cart too close to fixture",
    miscellaneous: "Replacement crystal ordered.",
    ems_called: false,
    medical_refused: false,
    police_involved: false,
    status: "sent_to_corporate",
    created_at: "2026-08-07T09:40:00Z",
    updated_at: "2026-08-07T14:00:00Z",
    reported_by_name: "Maria Lopez",
    hotel: HOTELS.find((h) => h.id === "1"),
  },
  {
    id: "4",
    report_number: "26-INC-10020",
    hotel_id: "14",
    incident_type: "employee_injury",
    severity: "high",
    incident_date_time: "2026-08-06T22:10",
    reported_date_time: "2026-08-06T22:25",
    location_detail: "Kitchen – dish area",
    subject_name: "Alex Thompson",
    subject_type: "Employee",
    subject_identifier: "EMP-4421",
    subject_phone: "",
    subject_email: "",
    witness_name: "Luis Gomez",
    witness_contact: "",
    narrative:
      "Associate slipped on wet floor near dish machine and fell, landing on right wrist. Ice applied on site. Associate was driven to urgent care.",
    actions_taken: "First aid, ice, transport to urgent care. Floor dried and wet-floor signs placed.",
    contributing_factors: "Standing water near dish machine",
    miscellaneous: "Workers comp claim started.",
    ems_called: false,
    medical_refused: false,
    police_involved: false,
    status: "closed",
    created_at: "2026-08-06T22:30:00Z",
    updated_at: "2026-08-07T11:00:00Z",
    reported_by_name: "Kitchen Supervisor",
    hotel: HOTELS.find((h) => h.id === "14"),
  },
];
